spring.datasource.url=jdbc:postgresql://localhost:5432/prioriza
spring.datasource.username=prioriza
spring.datasource.password=prioriza

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.schemas=public

